// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFuMYF9jIPrsuf_0robZbboWAo7n2bxCQ',
    appId: '1:301066581179:web:a73f2a046bd854be96a59e',
    messagingSenderId: '301066581179',
    projectId: 'skin-scanning',
    authDomain: 'skin-scanning.firebaseapp.com',
    storageBucket: 'skin-scanning.firebasestorage.app',
    measurementId: 'G-LR7MENQ9ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hsvZf7hRfe-hQkBMhjD9LWFQ48S6E3E',
    appId: '1:301066581179:android:7969d62ddc6fb91996a59e',
    messagingSenderId: '301066581179',
    projectId: 'skin-scanning',
    storageBucket: 'skin-scanning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywpdVNYKrDvV8pHq4vKN_e2iRoAJyQlQ',
    appId: '1:301066581179:ios:9638072395e2d4df96a59e',
    messagingSenderId: '301066581179',
    projectId: 'skin-scanning',
    storageBucket: 'skin-scanning.firebasestorage.app',
    iosBundleId: 'com.example.skinscanning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywpdVNYKrDvV8pHq4vKN_e2iRoAJyQlQ',
    appId: '1:301066581179:ios:9638072395e2d4df96a59e',
    messagingSenderId: '301066581179',
    projectId: 'skin-scanning',
    storageBucket: 'skin-scanning.firebasestorage.app',
    iosBundleId: 'com.example.skinscanning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFuMYF9jIPrsuf_0robZbboWAo7n2bxCQ',
    appId: '1:301066581179:web:c5929cd7a3251fbb96a59e',
    messagingSenderId: '301066581179',
    projectId: 'skin-scanning',
    authDomain: 'skin-scanning.firebaseapp.com',
    storageBucket: 'skin-scanning.firebasestorage.app',
    measurementId: 'G-YM2GNJQEGV',
  );
}
